target:	hw6

hw6:    main.cpp Data.cpp Catalog.cpp BookCatalog.cpp MusicCatalog.cpp MovieCatalog.cpp
		g++ -std=c++11 main.cpp Data.cpp Catalog.cpp BookCatalog.cpp MusicCatalog.cpp MovieCatalog.cpp -o hw6

clean:
		rm hw6
